name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v1

      - name: Zip smartthings dir
        run: |
          cd /home/runner/work/Home-Assistant-test-components-SmartThings/Home-Assistant-test-components-SmartThings/custom_components/smartthings
          zip smartthings.zip -r ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/Home-Assistant-test-components-SmartThings/Home-Assistant-test-components-SmartThings/custom_components/smartthings/smartthings.zip
          asset_name: smartthings.zip
          tag: ${{ github.ref }}
          overwrite: true